# Generated by Django 2.0.2 on 2018-03-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tree_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tree', to='app.Tree'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='date_added',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_last_updated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dod',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='father_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='father', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='prefix',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
