# Generated by Django 2.0.2 on 2018-03-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180322_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='tree_id',
            new_name='tree',
        ),
        migrations.RemoveField(
            model_name='marriage',
            name='husband_id',
        ),
        migrations.RemoveField(
            model_name='marriage',
            name='wife_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='father_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mother_id',
        ),
        migrations.AddField(
            model_name='marriage',
            name='husband',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='marriage_husband', to='app.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marriage',
            name='wife',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='marriage_wife', to='app.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_father', to='app.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_mother', to='app.Person'),
        ),
    ]
