# Generated by Django 2.0.2 on 2018-04-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180405_1304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marriage',
            unique_together={('husband', 'wife')},
        ),
    ]
