# Generated by Django 2.0.2 on 2018-04-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180405_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriage',
            name='tree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='marriage_tree', to='app.Tree'),
            preserve_default=False,
        ),
    ]
