# Generated by Django 2.0.2 on 2018-04-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_marriage_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1),
        ),
    ]
