# Generated by Django 2.0.2 on 2018-04-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180417_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
