# Generated by Django 2.0.2 on 2018-04-19 09:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_person_is_root'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
