# Generated by Django 2.0.2 on 2018-04-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180419_1248'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
    ]
