# Generated by Django 2.0.2 on 2018-04-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180419_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriage',
            name='husband',
            field=models.ForeignKey(limit_choices_to={'gender': 'm'}, on_delete=django.db.models.deletion.PROTECT, related_name='husband_of', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='wife',
            field=models.ForeignKey(limit_choices_to={'gender': 'f'}, on_delete=django.db.models.deletion.PROTECT, related_name='wife_of', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='father',
            field=models.ForeignKey(limit_choices_to={'gender': 'm'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_of_father', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(limit_choices_to={'gender': 'f'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_of_mother', to='app.Person'),
        ),
    ]
