# Generated by Django 2.0.2 on 2018-08-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180420_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_paternal_desc',
            field=models.BooleanField(default=True),
        ),
    ]
