# Generated by Django 2.0.2 on 2018-08-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_person_is_paternal_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dod',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
