# Generated by Django 2.0.2 on 2018-08-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180816_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('f', 'أنثى'), ('m', 'ذكر')], max_length=1),
        ),
    ]
