# Generated by Django 2.0.2 on 2018-08-25 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180825_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_last_updated',
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
