# Generated by Django 2.0.2 on 2018-08-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180825_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='passcode',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
