# Generated by Django 2.0.2 on 2018-08-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_tree_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='passcode',
            field=models.CharField(max_length=50),
        ),
    ]
